apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: belajar-nodejs-dasar
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: app=fegisp/belajar-nodejs-dasar
    argocd-image-updater.argoproj.io/app.update-strategy: semver:^v
spec:
  project: default
  source:
    repoURL: https://github.com/fegisucepto/belajar-nodejs-dasar.git
    path: k8s
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: belajar-nodejs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
